### ISSUE TITLE
CUTEst failed to build on OSX 10.11.1

### ISSUE THREAD

**Issue by ohinder** [optimizers/homebrew-cutest#12]
Hey, I am getting an error when I use homebrew-cutest

https://gist.github.com/c560944a3f10ba8f7afb

Here is the error:

 Compiling ral_nlls_dummy 		ral_nlls_dummy.f90:183:32:

      CALL eval_F( status, n, m, X, WORK_real( start_f ), params )
                                1
Error: Type mismatch in argument 'x' at (1); passed REAL(4) to REAL(8)
 => Disabling optimization ral_nlls_dummy.f90:183:32:

      CALL eval_F( status, n, m, X, WORK_real( start_f ), params )
                                1
Error: Type mismatch in argument 'x' at (1); passed REAL(4) to REAL(8)
make[1]: *** [/private/tmp/cutest20160122-61751-1893kap/objects/mac64.osx.gfo/single/ral_nlls_dummy.o] Error 1
make: *** [all_single] Error 2

**Comment by abelsiqueira** [comment]
This happens on the [CUTEst without homebrew](http://ccpforge.cse.rl.ac.uk/gf/project/cutest/wiki/) too, but only if you choose to compile single precision.
It happens because some code in `src/ral_nlls` is using `c_double`.

One solution would be drop single support here on homebrew-cutest. Would it break for someone?

Another solution would be change the code itself. Maybe excluding `ral_nlls` for single precision.

**Comment by dpo** [comment]
Should get fixed in HEAD soon.

**Comment by ohinder** [comment]
excellent! thanks.

**Comment by dpo** [comment]
Should be fixed now. It works for me. Could you give it a go?

**Comment by abelsiqueira** [comment]
It is working on Linux again.

**Comment by dpo** [comment]
Excellent, thank you. I'll work on stable releases ASAP.
